title: Organic Maps
tagline: Fast detailed offline maps for travelers, tourists, hikers and cyclists
description: > 
  Fast detailed offline maps for travelers, tourists, hikers and cyclists
  curated with love by MAPS.ME founders
logo: android-chrome-512x512.png
image: card.png
twitter:
  card: summary_large_image
  username: OrganicMapsApp
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
